name: App Preview Deployment

on: 
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Create env file
      run: |
        touch .env
        echo MONGO_DETAILS=${{ secrets.MONGO_DETAILS }} >> .env
        echo secret=${{ secrets.secret_key }} >> .env
        cat .env    
    
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Create namespace
      uses: okteto/create-namespace@master
      with:
        namespace: pr-${{ github.event.number }}-youngestdev
   
    - name: Deploy application
      uses: okteto/deploy-stack@master
      with:
        build: "true"
        namespace: pr-${{ github.event.number }}-youngestdev

    - name: add comment to PR
      uses: okteto/notify-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: "Preview environment available at https://fastapi-pr-${{ github.event.number }}-youngestdev.cloud.okteto.net" 
